const companyList = [
  '1Password',
  '23andMe',
  '3M',
  'A&E Network',
  'ABB',
  'ABC',
  'ADP',
  'ADTRAN',
  'AF Group',
  'AGS Automotive',
  'AIG',
  'AKQA',
  'AMD',
  'APCO Worldwide',
  'ARM',
  'ASRC Federal',
  'AT&T',
  'AXS',
  'Accenture',
  'Accion Systems',
  'Activision/Blizzard',
  'Ad Council',
  'Adidas',
  'Adobe',
  'Aflac',
  'Airbnb',
  'Akamai Technologies',
  'Akuna Capital',
  'Alarm.com',
  'Alaska Airlines',
  'Alexander Group',
  'AlixPartners',
  'Allen & Gerritsen',
  'AllianceBernstein',
  'AlphaSights',
  'Amazon',
  'Amazon Robotics',
  'American Airlines',
  'American Express',
  'Amgen',
  'Amtrak',
  'Anaplan',
  'Ancestry',
  'Anheuser-Busch InBev',
  'Ankura',
  'Anyscale',
  'Aon',
  'Apache Corporation',
  'AppFolio',
  'Appian',
  'Apple',
  'Applied Materials',
  'Applied Medical',
  'ArcelorMittal',
  'Ares Management',
  'Argo AI',
  'Argonne National Laboratory',
  'Arista Networks',
  'Arthrex',
  'Asana',
  'Atlassian',
  'Audible',
  'Aurora',
  'Autodesk',
  'AvidXchange',
  'BEA Systems',
  'BECU',
  'BMV Group',
  'BNP Paribas',
  'BP',
  'BSH',
  'Bain & Company',
  'Baker Hughes',
  'Bank of America',
  'Bank of Montreal',
  'Bank of the West',
  'Barclays',
  'Bartle Bogle Hegarty',
  'Becton Dickinson',
  'Belvedere trading',
  'Benevity',
  'Bently Systems',
  'Best Buy',
  'Bethesda',
  'Beyond Limits',
  'Big Spaceship',
  'BlackRock',
  'Blackbaud',
  'Blackhawk Network',
  'Blackstone',
  'Blade',
  'Blend',
  'Bloomberg',
  'BluJay Solutions',
  "Boar's Head Brand",
  'Bobcat',
  'Boeing',
  'Boom Supersonic',
  'Booz Allen Hamilton',
  'Bosch',
  'Boston Consulting Group (BCG)',
  'Boston Scientific',
  'Braze',
  'Bright Health',
  'Bristol Myers Squibb',
  'British Airways',
  'Broadsign',
  'Brookings Institution',
  'BuzzFeed',
  'ByteDance',
  'CB Insights',
  'CBIZ',
  'CBS Interactive',
  'CF Industries',
  'CGI',
  'CH Robinson',
  'CME Group',
  'COVID-19 Summer 2020 Internship Status List',
  'CVS/Aetna',
  'Callaway Golf',
  'Calvin Klein',
  'Cannon',
  'Cantor Fitzgerald',
  'Capital Group',
  'Capital One',
  'Capitol Music Group',
  'Captify',
  'Cardinal Health',
  'Carfax',
  'Carvana',
  'Caterpillar',
  'Cedar Fair Amusement',
  'CenturyLink',
  'Cerner Corporation',
  'Charles Schwab',
  'Chartbeat',
  'Checkr',
  'Chegg',
  'Chesapeake Energy',
  'Chevron',
  'Chewy',
  'Chick-Fill-A',
  'Cigna',
  'Cisco',
  'Cisco Meraki',
  'Citadel',
  'Citi',
  'Citrix Systems',
  'Civis Analytics',
  'Clairvoyant LLC',
  'Clorox',
  'Cloudflare',
  'Cognizant',
  'Coinbase',
  'College Board',
  'Collins Aerospace',
  'Comcast',
  'CommScope',
  'Commonwealth Care Alliance',
  'Company',
  'ConocoPhillips',
  'Constant Contact',
  'Continental',
  'Converse',
  'Convoy',
  'Coveo',
  'Cox Enterpise',
  'Crayola',
  'Creative Artists Agency',
  'Credit Suisse',
  'CrossInstall',
  'CrowdStrike',
  'Cruise Automation',
  'Cubic',
  'Cummins',
  'Custom Ink',
  'D.E. Shaw Group',
  'DAAD-WISE',
  'DNAnexus',
  'DRW',
  'Dassault Systems',
  'DataScan',
  'Databricks',
  'Dataminr',
  'Datto',
  'DeepMap',
  'DeepSource',
  'Defense Counterintelligence and Security Agency',
  'Dell',
  'Deloitte',
  'Delta Airline',
  'Dematic',
  'Designer Brands',
  'Deutsche Bank',
  'Dexcom',
  'Diff',
  'DigitalOcean',
  'Dillards',
  'Discover Financial Services',
  'Discovery Inc.',
  'Dish Netowrks',
  'Disney',
  'Ditto PR',
  'DocuSign',
  'Dolby',
  'DoorDash',
  'Dow',
  'Dow Jones',
  'Downtown',
  'DraftKings',
  'Draper Laboratory',
  'DriveTime',
  'Dropbox',
  'Duff & Phelps',
  'EF Education First',
  'ERCOT (Energy Reliability Council of Texas)',
  'EVERFI',
  'EY-Parthenon',
  'Earnest',
  'Ebay',
  'Echostar',
  'Elanco',
  'Electronic Arts',
  'Eli Lilly',
  'Epsilon',
  'Equinix',
  'Ernst & Young (EY)',
  'Esri',
  'Etsy',
  'EverQuote',
  'Excellus Blue Cross Blue Shield',
  'Expedia',
  'ExtraHop',
  'ExxonMobil',
  'F5 Networks',
  'FBI',
  'FINRA',
  'FIS',
  'FTI Consulting',
  'FX',
  'Facebook',
  'FactSet',
  'Fandago',
  'Fannie Mae',
  'Fedex',
  'Fiat/FCA',
  'Fidelity Investments',
  'FireEye',
  'FirstEnergy',
  'Five Rings Capital',
  'Flexport',
  'Flipkart',
  'Flipp',
  'Forbes',
  'Ford Motor Company',
  'Formlabs',
  'Frame.io',
  'Framework',
  'Freeport-McMoRan',
  'Funding Circle',
  'GE Transportation-Wabtec',
  'GLAAD',
  'Gallagher',
  'Gap Inc.',
  'Garmin',
  'Gartner',
  'Gemography',
  'Genentech',
  'General Atomics',
  'General Electric',
  'General Motors',
  'Genuine Parts Company',
  'Georgia Pacific',
  'Gildan',
  'Giphy',
  'Glassdoor',
  'Globe Life',
  'GoCanvas',
  'GoDaddy',
  'Gojek',
  'GoldPoint Partners',
  'Golden 1 Credit Union',
  'Goldman Sachs',
  'Google',
  'Green Dot',
  'Green Hills Software',
  'Greenmantra',
  'Group Nine Media',
  'Groupe Dynamite',
  'Groupon',
  'Guideline',
  'Gulfstream Aerospace',
  'HARMAN',
  'HCA Healthcare',
  'HP',
  'HPE',
  'HSBC',
  'Halff Associates',
  'Halliburton',
  'Harkins',
  'Hartford Steam Boiler',
  'Hawaiian Airlines',
  'HealthScape',
  'Heartland Payment Systems',
  'Helen of Troy',
  'Hendrickson',
  'Hertz',
  'Hess Corporation',
  'Hill Holliday',
  'Hilton',
  'Honeywell',
  'HubSpot',
  'Hudson River Trading',
  'Hughes',
  'Huhtamaki',
  'Hulu',
  'Humana',
  'Husky Energy',
  'IBM',
  'IBM Research',
  'IDEMIA',
  'IDEO',
  'IDEX',
  'IDX Broker',
  'IGN',
  'IHS Markit',
  'IMC Trading',
  'IPG MediaBrands',
  'IQVIA',
  'Idexx Laboratories',
  'Improbable',
  'Indeed',
  'Indigo Ag',
  'Informatica',
  'Instabase',
  'Intel',
  'InterSystems',
  'Interbrand',
  'Interpublic Group',
  'Intuit',
  'Intuitive Surgical',
  'JDA Software',
  'JP Morgan',
  'Jam City',
  'Jane Street',
  'JetBlue',
  'John Deere',
  'Johnson and Johnson',
  'Jordan Blanchard Capital',
  'JumpTrading',
  'Juniper Networks',
  'Justworks',
  'KPMG',
  'Kabbage',
  'Kaiser Permanente',
  'Kayak',
  'Kearney',
  'Keen',
  'Kepler Group',
  'Ketsight Technologies',
  'Khan Academy',
  'Kiewit',
  'Kin and Carta',
  'Kitty Hawk',
  'Klick Health',
  'Koch Industries',
  "Kohl's",
  'Kohler Engines',
  'Kroger Digital',
  'L Brands',
  "L'Oréal",
  'L.L. Bean',
  'LEK consulting',
  'LLamasoft',
  'Lacework',
  'Lam Research',
  "Lands' End",
  'Latch',
  'LendingClub',
  'Lenovo',
  'Leo Burnett',
  'Liberty Mutual Insurance',
  'Lifeway Christian Resources',
  'Lime',
  'LinkedIn',
  'LiveRamp',
  'Lockheed Martin',
  'Lori Friedman-Revolution Financial Management',
  'Los Alamos National Labs',
  'Los Angeles Rams',
  "Lowe's",
  'Lyft',
  'M Booth',
  'M&T Bank',
  'MIT Lincoln Laboratory',
  'MITRE',
  "Macy's",
  'Magnopus',
  'Malwarebytes',
  'Manhattan Associates',
  'Manulife Canada',
  'Marathon Oil',
  'Marathon Petroleum',
  'Mark Cuban Companies',
  'Markel',
  'MarketAxess',
  'Marqeta',
  'Marriot',
  'Marsh and Mclennan Agency',
  'Masimo',
  'MassMutual',
  'Mastercard',
  'MathWorks',
  'Mattel',
  'Mayo Clinic',
  'McAfee',
  'McCann',
  'McKinsey & Company',
  'Medicus Healthcare Solutions',
  'Medline Industries',
  'Medtronic',
  'Mercedez Benz',
  'Mercer',
  'Micro Focus',
  'Micron',
  'Microsoft',
  'Mindbody',
  'Moelis & Company',
  'MongoDB',
  'Morgan Stanley',
  'Moss Adams',
  'Motorola Solutions',
  'MousePaw Media',
  'Mozilla',
  'Mulberry',
  'MullenLowe',
  'NASA',
  'NBC Olympic',
  'NBCUniversal',
  'NPR',
  'Nasdaq',
  'National Geographic',
  'National Institutes of Health',
  'National Security Agency',
  'Nationwide',
  'Naval Research Enterprise Internship Program',
  'Nelnet',
  'Nestle USA',
  'New York Air Brake',
  'New York Times',
  'Newell Brands',
  'Nextdoor',
  'Nielsen',
  'Nike',
  'Nintendo',
  'Nissan',
  'No Kid Hungry',
  'Noblis',
  'Nokia',
  'Nordstrom',
  'Norfolk Southern',
  'Northrop Grumman',
  'Northwest Permanente',
  'Northwestern Mutual',
  'Nutanix',
  'Nvidia',
  'OSIsoft',
  'Oak Ridge National Laboratory',
  'Oakland Athletes',
  'Obama Foundation',
  'Occidental Petroleum',
  'Okta',
  'Old Mission Capital',
  'Oliver Wyman',
  'OneWeb',
  'Open Water Accelerator',
  'OpenTable',
  'OppLoans',
  'Optimizely',
  'Optiver',
  'Oracle',
  'Orbis Investment',
  'Oscar Health',
  'Outlier',
  'Owens Corning',
  'PBS',
  'PGT Trucking',
  'PIMCO',
  'PJT Partners',
  'PROCEPT BioRobotics',
  'PSB',
  'Paccar',
  'Pacific Lift',
  'Paclintra',
  'Pagerduty',
  'Palantir',
  'Palo Alto Networks',
  'Pandora',
  'Paradox',
  'Pariveda Solutions',
  'Parker Hannifinn',
  'PayPal',
  'Paycom',
  'Paytm',
  'Pearson VUE',
  'Pegasystems',
  'Peloton',
  'PepsiCo',
  'Philips',
  "Phoenix Children's Hospital",
  'Ping Identity',
  'Pinterest',
  'Pioneer Natural Resources',
  'Piper Sandler',
  'Pixar Animation Studios',
  'Plaid',
  'PlayStation',
  'PluralSight',
  'Pogo',
  'Point72',
  'Pratt & Whitney',
  'PricewaterhouseCoopers',
  'Primer',
  'Procore',
  'Procter & Gamble (P&G)',
  'Proofpoint',
  'Protiviti',
  'Pure Storage',
  'Q2E Banking',
  'Qualcomm',
  'Qualtrics',
  'Quantcast',
  'QuantumScope',
  'Quicken Loans',
  'Quora',
  'R/GA',
  'REI',
  'ROI·DNA',
  'RSM',
  'Ramboll',
  'Randa Accessories',
  'Raytheon BBN',
  'Raytheon Technologies',
  'RedHat',
  'Reddit',
  'Redfin',
  'RefleXion Medical',
  'Regeneron Pharmaceuticals',
  'Rent The Runway',
  'ResMed',
  'Reuters',
  'Rexnord',
  'Ribbon Health',
  'RingCentral',
  'Ripcord',
  'Robert Half',
  'Robinhood',
  'Roblox',
  'Roche',
  'Roku',
  'Rolls-Royce',
  'Rowan',
  'Royal Bank of Canada (RBC)',
  'Rubrik',
  'SAP',
  'SAS',
  'SC Johnson',
  'SPS Commerce',
  'STV Inc',
  'SUEZ Water Technologies & Solutions',
  'Saatchi & Saatchi',
  'Salesforce',
  'Sallie Mae',
  'Samsara',
  'Samsung',
  'San Francisco MUNI',
  'Santander CIB',
  'Schlumberger',
  'Schneider Electric',
  'Scholastic',
  'Seagate',
  'Seattle Genetics, Inc.',
  'Secret Mission Software',
  'ServiceNow',
  'Shamrock Foods',
  'Sherwin Williams',
  'Shiseido',
  'Shopee',
  'Shopify',
  'Showpass',
  'Shuffle',
  'Shure',
  'Siemens',
  'Sigma Computing',
  'Simon Kucher & Partners',
  'Skip Hop',
  'Slack',
  'Slalom Build',
  'Sleep Number',
  'Sling TV',
  'Snap',
  'SnapTravel',
  'Snowflake',
  'Softheon',
  'Sonder',
  'Sonos',
  'Sony',
  'Sony Interactive Entertainment',
  'Sony Music',
  'Southwest Airlines',
  'Southwest Research Institute',
  'Southwestern Advantage',
  'SpaceX',
  'Splunk',
  'Spoiler Alert',
  'Spotify',
  'Springbuk',
  'Sprout Social',
  'Square',
  "St. Jude Children's Research Hospital",
  'Standard Chartered Bank GBS',
  'Stanford Health Care',
  'Starbucks',
  'State Farm',
  'StitchFix',
  'Strategic Education',
  'Strategy&',
  'Stripe',
  'Stryker',
  'Stubhub',
  'Stuller',
  'Sumo Logic',
  'SunPower',
  'SurveyMonkey',
  'Susquehanna International Group',
  'Sysco',
  'T-Mobile',
  'TJX',
  'TPRI',
  'Tableau',
  'Take-Two Interactive',
  'Talend',
  'Target',
  'Team One',
  'Tegna Inc.',
  'Tenable',
  'TerraClear',
  'Tesla',
  'Texas Instruments',
  'Textron Aviation',
  'The Aerospace Corporation',
  'The Boston Globe',
  'The Good Year Tire & Rubber Company',
  'The Hartford',
  'The Hut Group',
  'The Kennedy/Marshall Co',
  'The Motley Fool',
  'The Round',
  'Thermo Fisher Scientific',
  'Thomson Reuters',
  'Thumbtack',
  'Ticketmaster',
  'Tik Tok',
  'Tinder',
  'Toast',
  'Toyota Connected',
  'Toyota Research Institute',
  'TransUnion',
  'Transamerica',
  'TransferWise',
  'Travelers',
  'Trexquant',
  'TripAdvisor',
  'Truist Financial',
  'Trusaic',
  'TuSimple',
  'Twilio',
  'TwinStrand Biosciences',
  'Twitch',
  'Twitter',
  'Two Sigma',
  'UBS',
  'US Bank',
  'USAA',
  'USLI',
  'USTA 2020 D&I',
  'Uber',
  'Udemy',
  'Ugam Solutions',
  'UiPath',
  'Ultimate Software',
  'Under Armour',
  'United Airlines',
  'UnitedHealth Group',
  'Unity',
  'Universal McCann',
  'Universal Music Group',
  'Uplift',
  'Uponor',
  'Urban Outfitters (URBN)',
  'UserTesting',
  'VMLY&R',
  'VMware',
  'Valkyrie Investments',
  'Vanguard',
  'Vatic Labs',
  'Vergin Hyperloop One',
  'Verily',
  'Verisign',
  'Verizon',
  'Verso Booksv',
  'ViacomCBS',
  'Viasat',
  'Virgin Orbit',
  'Visa',
  'Volvo',
  'Vouch Insurance',
  'Vox',
  'Voya Financial',
  'WGBH',
  'WSP',
  'Wagner Spraytech',
  'Walmart',
  'Warner',
  'Warner Music Group',
  'WarnerMedia',
  'Wattpad',
  'Wayfair',
  'Waymo',
  'WePay',
  'WeRide.ai',
  'Wells Fargo',
  'Western Digital',
  'William Morris Endeavor',
  'Willis Towers Watson',
  'WillowTree',
  'Wish',
  'Wisk',
  'Wolfram',
  'Wolverine Trading',
  'Workday',
  'Xandr',
  'Xcel Energy',
  'Xilinx',
  'Y Combinator',
  'Yahoo (Verizon Media)',
  'Yelp',
  'Yubico',
  'ZS',
  'Zebra Technology',
  'Zenith Insurance',
  'Zillow',
  'Zipline',
  'Zippity Cars',
  'Zocdoc',
  'Zoom',
  'Zscaler',
  'Zymergen',
  'Zynga',
];
export default { companyList };
